[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)ephe/*'"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://astrogenie.netlify.app"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  ENABLE_NATIVE_MODULES = "true"
  LD_LIBRARY_PATH = "/usr/lib64"
  SWISSEPH_PATH = "/opt/build/repo/ephe"
  NPM_CONFIG_OPTIONAL = "false"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "swisseph-v2",
    "swisseph"
  ]
  included_files = ["ephe/*.se1"]

[functions.___netlify-server-handler]
  maxDuration = 30

[functions."next_api_calculate"]
  included_files = ["ephe/*.se1"]
  external_node_modules = ["swisseph-v2", "swisseph"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[dev]
  framework = "next"
  targetPort = 3000
