[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)ephe/*'"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://astrogenie.netlify.app"
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  ENABLE_NATIVE_MODULES = "true"
  LD_LIBRARY_PATH = "/usr/local/lib"
  SWISSEPH_PATH = "./ephe"
  NPM_CONFIG_OPTIONAL = "true"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  external_node_modules = [
    "swisseph-v2",
    "swisseph",
    "react-dom",
    "react-server-dom-webpack",
    "@opentelemetry/api"
  ]
  included_files = ["ephe/*.se1"]

[functions.___netlify-server-handler]
  maxDuration = 30

[functions.next_api_calculate]
  external_node_modules = [
    "swisseph-v2",
    "swisseph",
    "react-dom",
    "react-server-dom-webpack",
    "@opentelemetry/api"
  ]
  included_files = ["ephe/*.se1"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
